### ISSUE TITLE
did not recognize object of type "ImportDefaultSpecifier" 

### ISSUE THREAD

**Issue by ghost** [ghurlman/torii-azure-auth-sample#1]
### Hello !

When starting this project after a fresh install of this project (branch master today) on Debian with ember version :

> ember -v
> version: 0.2.0-beta.1
> node: 4.2.1
> npm: 2.1.8

I've got this error:

Serving on http://0.0.0.0:4200/
File: torii-azure-provider/initializers/app-version.js
did not recognize object of type "ImportDefaultSpecifier"
AssertionError: did not recognize object of type "ImportDefaultSpecifier"
   at Object.getFieldNames (/home/charles/tmp/torii-azure-auth-sample/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/recast/node_modules/ast-types/lib/types.js:581:12)
    at LocationFixer.LFp.fix (/home/charles/tmp/torii-azure-auth-sample/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/recast/lib/parser.js:85:23)
    at Array.forEach (native)
    at LocationFixer.LFp.fix (/home/charles/tmp/torii-azure-auth-sample/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/recast/lib/parser.js:57:14)
    at LocationFixer.LFp.fix (/home/charles/tmp/torii-azure-auth-sample/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/recast/lib/parser.js:87:14)
    at Array.forEach (native)
    at LocationFixer.LFp.fix (/home/charles/tmp/torii-azure-auth-sample/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/recast/lib/parser.js:57:14)
    at LocationFixer.LFp.fix (/home/charles/tmp/torii-azure-auth-sample/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/recast/lib/parser.js:87:14)
    at Object.exports.parse (/home/charles/tmp/torii-azure-auth-sample/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/recast/lib/parser.js:28:30)
    at Object.module.exports.compile (/home/charles/tmp/torii-azure-auth-sample/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/index.js:106:18)

**Comment by iorrah** [comment]
+1 The same issue here

```
$ ember server

version: 0.1.7
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: playon_client/initializers/export-application-global.js
did not recognize object of type "ImportDefaultSpecifier"
```

Current version

```
$ ember --version

version: 0.1.7
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.25
npm: 2.1.8
```

But when I type

```
$ npm --version
1.3.24
```

Maybe it's something wrong with node version or npm version.
Thank you for any help!

**Comment by nikolas** [comment]
I'm having this problem, too. ember-cli 0.1.15, npm 3.8.6 and node 4.2.6.
